spring.application.name=place-service
spring.datasource.url=jdbc:postgresql://localhost:5432/place
spring.datasource.username=seonhye
spring.datasource.password=1234

logging.level.iceapple.placeservice=debug;
